name: Always Fail

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

jobs:
  always_fail:
    runs-on: ubuntu-18.04
    steps:
      - name: Failing unconditionally
        run: false
